-- MySQL Script generated by MySQL Workbench
-- Sun Nov 24 16:59:31 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema facturacion
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `facturacion` ;

-- -----------------------------------------------------
-- Schema facturacion
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `facturacion` DEFAULT CHARACTER SET utf8 ;
SHOW WARNINGS;
USE `facturacion` ;

-- -----------------------------------------------------
-- Table `cities`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `cities` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `cities` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(55) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `roles`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `roles` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `roles` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL DEFAULT NULL,
  `status` TINYINT NULL DEFAULT NULL,
  `created` DATETIME NULL DEFAULT NULL,
  `modified` DATETIME NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `users`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `users` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `users` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `correo` VARCHAR(255) NOT NULL,
  `password` VARCHAR(255) NOT NULL,
  `verification` TINYINT NOT NULL DEFAULT 0,
  `token` VARCHAR(255) NULL,
  `role_id` INT NOT NULL,
  `status` TINYINT NULL DEFAULT NULL,
  `created` DATETIME NULL DEFAULT NULL,
  `modified` DATETIME NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_user_role1`
    FOREIGN KEY (`role_id`)
    REFERENCES `roles` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;

SHOW WARNINGS;
CREATE INDEX `fk_user_role1_idx` ON `users` (`role_id` ASC);

SHOW WARNINGS;
CREATE UNIQUE INDEX `email_UNIQUE` ON `users` (`correo` ASC);

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `persons`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `persons` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `persons` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `dni` INT(8) NULL,
  `name` VARCHAR(95) NULL DEFAULT NULL,
  `surname` VARCHAR(95) NULL DEFAULT NULL,
  `civil_status` INT NULL DEFAULT NULL,
  `phone` VARCHAR(45) NULL DEFAULT NULL,
  `contact` VARCHAR(245) NULL DEFAULT NULL,
  `code` VARCHAR(11) NULL DEFAULT NULL,
  `city_id` INT NULL DEFAULT NULL,
  `user_id` INT NOT NULL,
  `status` TINYINT NULL DEFAULT NULL,
  `created` DATETIME NULL DEFAULT NULL,
  `modified` DATETIME NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_person_city1`
    FOREIGN KEY (`city_id`)
    REFERENCES `cities` (`id`)
    ON DELETE SET NULL
    ON UPDATE CASCADE,
  CONSTRAINT `fk_person_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `users` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;

SHOW WARNINGS;
CREATE INDEX `fk_person_city_idx` ON `persons` (`city_id` ASC);

SHOW WARNINGS;
CREATE INDEX `fk_person_user1_idx` ON `persons` (`user_id` ASC);

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `providers`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `providers` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `providers` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `person_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_provider_person1`
    FOREIGN KEY (`person_id`)
    REFERENCES `persons` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;

SHOW WARNINGS;
CREATE INDEX `fk_provider_person1_idx` ON `providers` (`person_id` ASC);

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `warehouses`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `warehouses` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `warehouses` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL DEFAULT NULL,
  `status` TINYINT NULL DEFAULT NULL,
  `created` DATETIME NULL DEFAULT NULL,
  `modified` DATETIME NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `product_types`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `product_types` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `product_types` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `products`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `products` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `products` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `description` VARCHAR(245) NULL DEFAULT NULL,
  `quantity` INT NULL DEFAULT NULL,
  `product_type_id` INT NULL DEFAULT NULL,
  `status` TINYINT NULL DEFAULT NULL,
  `created` DATETIME NULL DEFAULT NULL,
  `modified` DATETIME NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_product_product_type1`
    FOREIGN KEY (`product_type_id`)
    REFERENCES `product_types` (`id`)
    ON DELETE SET NULL
    ON UPDATE CASCADE)
ENGINE = InnoDB;

SHOW WARNINGS;
CREATE INDEX `fk_product_product_type1_idx` ON `products` (`product_type_id` ASC);

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `products_warehouses`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `products_warehouses` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `products_warehouses` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `warehouse_id` INT NOT NULL,
  `product_id` INT NOT NULL,
  `stock` INT NULL DEFAULT NULL,
  `date` DATETIME NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_products_warehouses_warehouses1`
    FOREIGN KEY (`warehouse_id`)
    REFERENCES `warehouses` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_product_warehouse_product1`
    FOREIGN KEY (`product_id`)
    REFERENCES `products` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;

SHOW WARNINGS;
CREATE INDEX `fk_product_warehouse_warehouse1_idx` ON `products_warehouses` (`warehouse_id` ASC);

SHOW WARNINGS;
CREATE INDEX `fk_product_warehouse_product1_idx` ON `products_warehouses` (`product_id` ASC);

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `products_providers`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `products_providers` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `products_providers` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `product_id` INT NOT NULL,
  `provider_id` INT NOT NULL,
  `stock` INT NULL DEFAULT NULL,
  `price` FLOAT NULL DEFAULT NULL,
  `date` DATETIME NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_product_provider_product1`
    FOREIGN KEY (`product_id`)
    REFERENCES `products` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_product_provider_provider1`
    FOREIGN KEY (`provider_id`)
    REFERENCES `providers` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;

SHOW WARNINGS;
CREATE INDEX `fk_product_provider_product1_idx` ON `products_providers` (`product_id` ASC);

SHOW WARNINGS;
CREATE INDEX `fk_product_provider_provider1_idx` ON `products_providers` (`provider_id` ASC);

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `sellers`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `sellers` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `sellers` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `person_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_seller_person`
    FOREIGN KEY (`person_id`)
    REFERENCES `persons` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;

SHOW WARNINGS;
CREATE INDEX `fk_seller_person1_idx` ON `sellers` (`person_id` ASC);

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `clients`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `clients` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `clients` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `person_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_client_person1`
    FOREIGN KEY (`person_id`)
    REFERENCES `persons` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;

SHOW WARNINGS;
CREATE INDEX `fk_client_person1_idx` ON `clients` (`person_id` ASC);

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `voucher_types`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `voucher_types` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `voucher_types` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `voucher_headers`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `voucher_headers` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `voucher_headers` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `issue_date` DATETIME NULL DEFAULT NULL,
  `voucher_type_id` INT NOT NULL,
  `seller_id` INT NOT NULL,
  `client_id` INT NOT NULL,
  `status` TINYINT NULL DEFAULT NULL,
  `created` DATETIME NULL DEFAULT NULL,
  `modified` DATETIME NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_voucher_header_voucher_type1`
    FOREIGN KEY (`voucher_type_id`)
    REFERENCES `voucher_types` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_voucher_header_seller1`
    FOREIGN KEY (`seller_id`)
    REFERENCES `sellers` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_voucher_header_client1`
    FOREIGN KEY (`client_id`)
    REFERENCES `clients` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;

SHOW WARNINGS;
CREATE INDEX `fk_voucher_header_voucher_type1_idx` ON `voucher_headers` (`voucher_type_id` ASC);

SHOW WARNINGS;
CREATE INDEX `fk_voucher_header_seller1_idx` ON `voucher_headers` (`seller_id` ASC);

SHOW WARNINGS;
CREATE INDEX `fk_voucher_header_client1_idx` ON `voucher_headers` (`client_id` ASC);

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `voucher_details`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `voucher_details` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `voucher_details` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `stock` INT NULL DEFAULT NULL,
  `price` FLOAT NULL DEFAULT NULL,
  `product_id` INT NOT NULL,
  `voucher_header_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_voucher_detail_product1`
    FOREIGN KEY (`product_id`)
    REFERENCES `products` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_voucher_detail_voucher_header1`
    FOREIGN KEY (`voucher_header_id`)
    REFERENCES `voucher_headers` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;

SHOW WARNINGS;
CREATE INDEX `fk_voucher_detail_product1_idx` ON `voucher_details` (`product_id` ASC);

SHOW WARNINGS;
CREATE INDEX `fk_voucher_detail_voucher_header1_idx` ON `voucher_details` (`voucher_header_id` ASC);

SHOW WARNINGS;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
